version: "2"
linters:
  enable:
    - revive
    - usestdlibvars
  settings:
    revive:
      rules:
        - name: "exported"
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1003
        - -ST1000
        - -ST1003
        - -ST1005
        - -ST1020
        - -ST1021
        - -ST1022
formatters:
  enable:
    - gofmt
