name: Windows CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - run: go build -race
      - run: go test -race -timeout 60s ./...
